on:
  push:
    branches:
      - adf_publish

jobs:
  deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: adf_publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: 'RG1'
          dataFactoryName: 'ADF1V2-QA'
          armTemplateFile: 'ADF1V2/ARMTemplateForFactory.json'
          armTemplateParametersFile: 'ADF1V2/ARMTemplateParametersForFactory.json'
          additionalParameters: '-LS_KeyVault_Dev_properties_typeProperties_baseUrl "https://kv-qa-vp.vault.azure.net/" -AzureSqlDatabase1_properties_parameters_DatabaseName_defaultValue "SQL1VPDB"'
